name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          submodules: true

      - name: Dependencies
        run: ./.github/workflows/release-deps.sh

      - name: Release
        run: ./.github/workflows/release.sh
